### ISSUE TITLE
Support for Laravel 5.7

### ISSUE THREAD

**Issue by lmartins** [nzesalem/lastus#4]
Hi,

Is there an ETA on when you will release a version compatible with Laravel 5.7?

Thank you

**Comment by nzesalem** [comment]
Hello @lmartins, have you tried using the package in Laravel 5.7 without success?

**Comment by lmartins** [comment]
@nzesalem hey, sorry for the delay on my answer.
Yeah, when I try to upgrade the framework I get this error from Composer:
```
    - nzesalem/lastus v1.2.0 requires illuminate/support 5.6.x -> satisfiable by laravel/framework[5.6.x-dev], illuminate/support[5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
```

**Comment by nzesalem** [comment]
Okay, @lmartins, I look into it and hopefully do a new release over the weekend.
